SELECT  1 FROM DUAL;
/*
INSERT INTO ACCOUNT (USERNAME, PASSWORD, ROLE) VALUES ('admin@gmail.com', '1234', 'ADMIN');
INSERT INTO ACCOUNT (USERNAME, PASSWORD, ROLE) VALUES ('user@gmail.com' , '1234', 'USER');
INSERT INTO ACCOUNT (USERNAME, PASSWORD, ROLE) VALUES ('user1@gmail.com', '1234', 'ADMIN');*/
